tasks:
  - init: |
      pip3 install -r docs/doc-requirements.txt
      pip3 install -e.
    command: |
      cd docs && make html &&  cd build/html && python3 -m http.server 8080
    name: Sphinx preview
ports:
- port: 8080
