dist: xenial
language: python
sudo: required
cache: pip
services:
- docker
python:
- 3.8
install:
# Make a wheel and install it to test to catch possible
# issues with releases
- pip install --upgrade setuptools pip
- pip install -r dev-requirements.txt
- python setup.py bdist_wheel
- pip install dist/*.whl
- pip freeze
script:
- |
  # run autoformat
  if [[ "$REPO_TYPE" == "lint" ]]; then
    pre-commit run --all-files
  fi
after_success:
- pip install codecov
- pushd tests && codecov && popd

after_failure:
- |
  # point to auto-lint-fix
  echo "You can install pre-commit hooks to automatically run formatting"
  echo "on each commit with:"
  echo "    pre-commit install"
  echo "or you can run by hand on staged files with"
  echo "    pre-commit run"
  echo "or after-the-fact on already committed files with"
  echo "    pre-commit run --all-files"

deploy:
  provider: pypi
  user: mybinderteam
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: jupyterhub/repo2docker
  password:
    secure: Vcbr4UtckHRjKKhOFKyHkmBQRB9H3SnJvOoxuqXhzCR6JtVe2L1m4UJaSk5aq6CDauZI6fejYhMxJ6W5oqz2q7DH8RnemIVCmTaqTNqblQy6s1XK7iUjtWUtr+MfjFWNx99hqAy9VGVoi++9w4ZaDba448D69rkzVqQTJUjHTlJql66ZIyuPWLhgkWRxMNd5Hnwjf+ETc7efasD2NsvsASsI0AEZijjb+Lbi9V+hR1e1JTn+a8Gz4zskPGVT2kMTobLGE6ucfsYyPy/FxAp5GedEZdAaipjdHmN64ylV8fxDrsCKj4zwD+w43XJzJPJVpqmeYm93SKhWr2v5xn/IGFH/Ea/9/rzFogpDdCUIgv4/xNKgVFVaMalTSUs9aOwYoBVFrmWNkyPSv7vihgWtO2ljo239Eb81SHMiwnbsHG5Ao0XY32USn7CmLO7/BbnY+JVJpNHWoG/jdTn73OzXextGK30f7fp1IxSxhnGdMBkNbKeujOfmhtDj1DIyMM2eNy0YMprv90+d9zxn15PG3TjspXzM6d9wd7BhmuPfMnD6pC51l83S7kmTMJ9nK+WexACpZ0+jwLYsJUnwXClD4S1nZxaEW6cMfSEYFU/l93eyBQqiQC0EjvWCBXwfl8ZMVQr3gr/ZbqCVSaqtINri4JqA3iqHJl3mEdA2WJ5VDZw=
